### PR TITLE
Added Support for the Adafruit TLC5947 24-Channel PWM Driver

### PR DESCRIPTION
**Pull request by balzreber**
Added Support for the Adafruit TLC5947 24-Channel PWM Driver

### CODE REVIEW

**Comment by astagi** [comment]
Thank you :) I'm checking it!

**Comment by astagi** [comment]
Manually merged! :) thanks a lot!

**Comment by astagi** [comment]
Please @balzreber can you try using the firmware version from the repository and see if it works for you? :) it should..

**Comment by balzreber** [comment]
@astagi I'm not sure if you want me to rebranch and recreate the pull-request with the git repo, because I used the pipy files. Although as far as I can see, you manually merged all the files into the repo. Not sure if I'm wrong here? Or did you ask me just for testing purposes?
BTW: Thanks again for your help. I would not be able to push my project as far as I have, without nanpy ;-)

**Comment by astagi** [comment]
@balzreber no PR has been merged and nanpy 0.9.5 released :) I asked you to try the firmware now just for testing purpose.. Now the new firmware is on pypi, if you have the chance to test it let me know if it works :) https://pypi.python.org/packages/source/n/nanpy/nanpy-firmware-0.9.5.tar.gz#md5=97d1c1b0f65c60d8e0d9ed3518446e9c

Glad that Nanpy helped you to reach your goal :)

**Comment by balzreber** [comment]
@astagi just tested 0.9.5. works like a charm ;-)

**Comment by astagi** [comment]
oh yeah nice to know :) thank you @balzreber !

**Comment by astagi** [comment]
Oh @balzreber please send me another PR both on nanpy and nanpy-firmware and add yourself to CONTRIBUTORS file! :)

**Pull request closed without merging**
