### PR TITLE
MCP41xxx addition

### PR DESCRIPTION
**Pull request by egarris2**
Added support for the MCP41xxx library to control MCP41xxx digital potentiometers.

https://github.com/ArduinoMax/MCP41xxx

### CODE REVIEW

**Comment by astagi** [comment]
Thanks for this @egarris2 ! I'll merge this and I'll try to find out why CI doesn't pass

**Comment by egarris2** [comment]
Thanks @astagi !

**Comment by ponty** [comment]
One problem is that this line is missing from sample_cfg.h
```c
#define USE_MCP41xxx 0
```

The test is based on sample_cfg.h

**Comment by astagi** [comment]
Yeah that's true! I'll try it, thanks @ponty

**Comment by astagi** [comment]
SPI.h: No such file or directory

**Comment by ponty** [comment]
fixed!

**Pull request merged**
